# Generated by Django 3.1.7 on 2021-03-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_auto_20210315_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='tags',
        ),
    ]
