# Generated by Django 3.1.7 on 2021-03-18 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('bookmark', '0008_auto_20210318_2058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='tags',
            field=models.ManyToManyField(related_name='bookmark_tags', to='tags.Tag'),
        ),
    ]
