# Generated by Django 3.1.7 on 2021-03-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20210313_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
