# Generated by Django 3.1.7 on 2021-03-18 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20210318_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
