# Generated by Django 3.1.7 on 2021-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20210318_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='item_type',
            field=models.CharField(default='Todo', max_length=16),
        ),
    ]
