# Generated by Django 3.1.7 on 2021-03-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_auto_20210316_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(default=None, null=True, to='note.Tag'),
        ),
    ]
