# Generated by Django 3.1.7 on 2021-03-16 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0011_auto_20210316_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='card_description',
            field=models.TextField(max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
