# Generated by Django 3.1.7 on 2021-03-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0013_auto_20210316_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(to='note.Tag'),
        ),
    ]
