# Generated by Django 3.1.7 on 2021-03-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0015_auto_20210318_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='note.Tag'),
        ),
    ]
