# Generated by Django 3.1.7 on 2021-03-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
        ('note', '0016_auto_20210318_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='note_tags', to='tags.Tag'),
        ),
    ]
